### ISSUE TITLE
Generated licenses property is invalid

### ISSUE THREAD

**Issue by rgaiacs** [frictionlessdata/tableschema-ui#11]
# Overview

[Tabular Data Package JSON Schema](https://specs.frictionlessdata.io/schemas/tabular-data-package.json) (last updated on 2 May 2017) has

```
    "licenses": {
      ...
      "items": {
        "title": "License",
        "description": "A license for this descriptor.",
        "type": "object",
        "oneOf": [
          {
            "required": [
              "name"
            ]
          },
          {
            "required": [
              "path"
            ]
          }
        ],
      ...
    }
```

This means that `name` and `path` can **NOT** be present at the same time but https://create.frictionlessdata.io/ generates

```
  "licenses": [
    {
      "name": "CC0-1.0",
      "title": "CC0 1.0",
      "path": "https://creativecommons.org/publicdomain/zero/1.0/"
    }
  ]
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @rgaiacs,

Do you think it's a bug in the specs or in the library? TBH I'm not sure. At least I don't see a real reason to forbid providing both

**Comment by rgaiacs** [comment]
> At least I don't see a real reason to forbid providing both

The [documentation](https://specs.frictionlessdata.io/data-package/) says

> The object MUST contain a name property and/or a path property.

If you take this as the true, the JSON Schema has a bug because a JSON Schema validator (e.g. https://www.jsonschemavalidator.net/) will tell you

>  Found 1 error(s)
> Message: JSON is valid against more than one schema from 'oneOf'. Valid schema indexes: 0, 1.
> Schema path: #/properties/licenses/items/oneOf

for

```
  "licenses": [
    {
      "name": "CC0-1.0",
      "title": "CC0 1.0",
      "path": "https://creativecommons.org/publicdomain/zero/1.0/"
    }
  ]
```

**Comment by rgaiacs** [comment]
@roll I open a PR at https://github.com/frictionlessdata/specs/pull/799.

**Comment by roll** [comment]
FIXED in https://github.com/frictionlessdata/specs/pull/799
